### PR TITLE
Advanced Duplicator 2 Bug

### PR DESCRIPTION
**Pull request by TheMerkyShadow**
Advanced duplicator 2 has a check for Spawnable entities these two entities were set to false.

### CODE REVIEW

**Comment by X-Coder** [comment]
Just have seen your MR. This is one solution, but it has a bad side effect:
The entities are now listed in the entitiy spawnmenu, which is not good because these entities should only be spawned by the tools (or duplicators).

thegrb93 who added the line into advdupe2 code, which broke the old behavior, gave an explanation [here](https://github.com/wiremod/advdupe2/pull/33) on 8 Jan 2015.

So the solution is, but it requires a bit more code: The EntityClass needs to be registered to the duplicator. 

I already fixed it by using duplicator.RegisterEntityClass, I will add a commit+MR shortly after testing.

**Comment by TheMerkyShadow** [comment]
Only problem is that duplicator register class includes wires and such and we already have a system that does this? Would the two conflict?

**Comment by X-Coder** [comment]
Sorry I'm a bit confused, which two do you mean?

**Comment by X-Coder** [comment]
Check this commit: https://github.com/X-Coder/sbep/commit/2ceceda7246f46945af0faa1d11c78566c966f53
Where is this conflicting? Didn't find any conflicts in my tests yet.

**Comment by TheMerkyShadow** [comment]
Alright I didn't see that.
I was confused as well :)
Thanks for fixing the issue.
I think ur commit is good.

**Pull request merged**
