### PR TITLE
Workshop preparations

### PR DESCRIPTION
**Pull request by thrimbor**
I rebased my old changes to the updated master branch.

Commit | Explanation
--------- | ---------------
9ccf131 | There were a lot of problems when trying to run SBEP on case-sensitive systems (such as Linux with ext4), so I renamed everything to lowercase as a first step. Keeping everything lowercase should help with not introducing new case-sensitivity-problems. Also, gmad forbids upper-case characters in filenames.
91060ea | To correctly load the renamed items I adjusted all the paths I could find.
8f66161 | The workshop doesn't allow textfiles, so I came up with a pure lua-based solution. It may not be perfect, since my lua skills aren't that great, but it seemed to get the job done.
7afbdbd | As a last step, the addon.json to be able to create gma-files with gmad.

After these changes, SBEP should be workshop-compatible (gmad does create a gma-file).

### CODE REVIEW

**Comment by generalwrex** [comment]
Has this been tested on Linux?  If not i'll create a workshop branch here as well, really don't want to merge any major changes into master until its known for sure ;D

**Comment by SnakeSVx** [comment]
If this has been tested, which is I guess has happened. We could just merge into the master as well. Saves the time having to create new branches for it.

**Comment by generalwrex** [comment]
Yeah i was about to merge it now ;) It looks great

**Comment by thrimbor** [comment]
I tested the changes back when I originally made them (back in 2014) and then just rebased them onto the current state of the repository. I didn't have Garry's Mod installed on Linux for the past months, but I downloaded it last night and it did seem to work (SBEP got loaded and I was able to spawn some models), didn't have the time to try out anything more complex though, but since it worked back then it should work now, too.

**Comment by generalwrex** [comment]
Awesome thanks man!

**Pull request merged**
